### ISSUE TITLE
Wrong name for nuspec Authors replacement token

### ISSUE THREAD

**Issue by Lucidiot** [NuGet/docs.microsoft.com-nuget#1072]
It seems the `$author$` replacement token has changed to `$authors$`, as I randomly found out with [this comment](https://github.com/NuGet/Home/issues/4234#issuecomment-310849744) on a GitHub issue, but $author$ is still used throughout the nuspec docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec#replacement-tokens)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by StingyJack** [comment]
The observed behavior is that `$author$` is required, not `$authors$`

With `$authors$` in the nuspec
``` batch
E:\project\FTPSClient\FTPSClient>nuget pack FTPSClient.csproj  -verbosity detailed -version 0.1.2
NuGet Version: 4.1.0.2450
Attempting to build package from 'FTPSClient.csproj'.
MSBuild auto-detection: using msbuild version '15.9.21.664' from 'F:\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Packing files from 'E:\project\FTPSClient\FTPSClient\bin\Debug'.
Using 'FTPSClient.nuspec' for metadata.
System.Exception: Authors is required.
   at NuGet.Packaging.Manifest.Validate(Manifest manifest)
   at NuGet.Packaging.Manifest.ReadFrom(Stream stream, Func`2 propertyProvider, Boolean validateSchema)
   at NuGet.CommandLine.ProjectFactory.ProcessNuspec(PackageBuilder builder, String basePath)
   at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded, PackageBuilder builder)
   at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

with `$author$` in the nuspec and the `[AssemblyCompany]` attribute set.
``` batch
E:\project\FTPSClient\FTPSClient>nuget pack FTPSClient.csproj  -verbosity detailed -version 0.1.2
NuGet Version: 4.1.0.2450
Attempting to build package from 'FTPSClient.csproj'.
MSBuild auto-detection: using msbuild version '15.9.21.664' from 'F:\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Packing files from 'E:\project\FTPSClient\FTPSClient\bin\Debug'.
Using 'FTPSClient.nuspec' for metadata.
Add file 'E:\project\FTPSClient\FTPSClient\bin\Debug\AlexPilotti.FTPS.Client.dll' to package as 'lib\net472\AlexPilotti.FTPS.Client.dll'
Add file 'E:\project\FTPSClient\FTPSClient\bin\Debug\AlexPilotti.FTPS.Client.XML' to package as 'lib\net472\AlexPilotti.FTPS.Client.XML'

Id: AlexFTPS.v3
Version: 0.1.2
Authors: Alessandro Pilotti
Description: This is the latest AlexFTPS,a free FTP/FTPS client and class library for .net . It's written to overcome the limits of .Net's System.Net.FTPWebRequest in terms of FTPS support. See the original site @ http://ftps.codeplex.com or the repo that sourced this package https://github.com/StingyJack/FTPSClient for more details!
License Url: http://www.gnu.org/licenses/lgpl.html
Project Url: https://github.com/StingyJack/FTPSClient
Tags: AlexFTPS, FTP, FTPS
Dependencies:

Added file '[Content_Types].xml'.
Added file '_rels/.rels'.
Added file 'AlexFTPS.v3.nuspec'.
Added file 'lib/AlexPilotti.FTPS.Client.dll'.
Added file 'lib/AlexPilotti.FTPS.Client.pdb'.
Added file 'lib/AlexPilotti.FTPS.Client.XML'.
Added file 'lib/net472/AlexPilotti.FTPS.Client.dll'.
Added file 'lib/net472/AlexPilotti.FTPS.Client.XML'.
Added file 'package/services/metadata/core-properties/47da45ab69b143988bc9df7d1f0faa77.psmdcp'.

Successfully created package 'E:\project\FTPSClient\FTPSClient\AlexFTPS.v3.0.1.2.nupkg'.
WARNING: Issue found with package 'AlexFTPS.v3'.

WARNING: Issue: Assembly not inside a framework folder.
WARNING: Description: The assembly 'lib\AlexPilotti.FTPS.Client.dll' is placed directly under 'lib' folder. It is recommended that assemblies be placed inside a framework-specific folder.
WARNING: Solution: Move it into a framework-specific folder. If this assembly is targeted for multiple frameworks, ignore this warning.

WARNING: Issue: Consider providing Summary text.
WARNING: Description: The Description text is long but the Summary text is empty. This means the Description text will be truncated in the 'Manage NuGet Packages' dialog.
WARNING: Solution: Provide a brief summary of the package in the Summary field.

```

**Comment by Mikejo5000** [comment]
Looks like this was fixed
