### ISSUE TITLE
System.ArgumentException: Illegal characters in path.

### ISSUE THREAD

**Issue by jubalmurrian** [NuGet/docs.microsoft.com-nuget#1364]
**When updating an existing package to a new version, I receive the following exception "Illegal characters in path." when NuGet attempts to remove the existing package from the packages folder. It also creates a file named "SimpleInjector.4.5.1.deleteme" in the packages folder.**

Visual Studio Professional 2015 Version 14.0.25431.01 Update 3

NuGet Package Manager 3.6.0

Packages Folder Path: "C:\Workspaces\SoftwareNxT\nGenCandidate-Dev1\packages"

**Stack Trace:**

Attempting to gather dependency information for multiple packages with respect to project 'CandidateTest', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 47.82 ms
Attempting to resolve dependencies for multiple packages.
One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'SimpleInjector 4.4.3'
Resolving dependency information took 0 ms
Resolving actions install multiple packages
Retrieving package 'SimpleInjector 4.5.1' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/simpleinjector/4.5.1/simpleinjector.4.5.1.nupkg
Removed package 'SimpleInjector 4.4.3' from 'packages.config'
  OK https://api.nuget.org/v3-flatcontainer/simpleinjector/4.5.1/simpleinjector.4.5.1.nupkg 159ms
Installing SimpleInjector 4.5.1.
Successfully uninstalled 'SimpleInjector 4.4.3' from EllaChatBot
Adding package 'SimpleInjector.4.5.1' to folder 'C:\Workspaces\SoftwareNxT\nGenCandidate-Dev1\packages'
Install failed. Rolling back...
Package 'SimpleInjector 4.5.1' does not exist in project 'EllaChatBot'
Package 'SimpleInjector 4.4.3' already exists in folder 'C:\Workspaces\SoftwareNxT\nGenCandidate-Dev1\packages'
Added package 'SimpleInjector 4.4.3' to 'packages.config'
Removing package 'SimpleInjector 4.5.1' from folder 'C:\Workspaces\SoftwareNxT\nGenCandidate-Dev1\packages'
Illegal characters in path.
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at Microsoft.TeamFoundation.Common.FileSpec.GetFullPath(String path, Boolean checkForIllegalDollar)
   at Microsoft.TeamFoundation.VersionControl.Client.Client.GetLocalWorkspace(String localPath, Boolean throwIfNotFound)
   at NuGet.TeamFoundationServer.DefaultTFSSourceControlManager..ctor(ISettings settings, SourceControlBindings sourceControlBindings)
   at NuGet.TeamFoundationServer.TFSSourceControlManagerProvider.GetTFSSourceControlManager(SourceControlBindings sourceControlBindings)
   at NuGet.PackageManagement.VisualStudio.TFSSourceControlManagerProviderPicker.GetTFSSourceControlManager(SourceControlBindings sourceControlBindings)
   at NuGet.PackageManagement.VisualStudio.VSSourceControlManagerProvider.<>c__DisplayClass5_0.<GetSourceControlManager>b__1(ITFSSourceControlManagerProvider provider)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NuGet.PackageManagement.VisualStudio.VSSourceControlManagerProvider.<<GetSourceControlManager>b__5_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at NuGet.PackageManagement.VisualStudio.VSSourceControlManagerProvider.GetSourceControlManager()
   at NuGet.ProjectManagement.SourceControlUtility.GetSourceControlManager(INuGetProjectContext nuGetProjectContext)
   at NuGet.ProjectManagement.FileSystemUtility.DeleteFile(String fullPath, INuGetProjectContext nuGetProjectContext)
   at NuGet.ProjectManagement.FolderNuGetProject.DeletePackage(PackageIdentity packageIdentity, INuGetProjectContext nuGetProjectContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.<DeletePackage>d__75.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<>c__DisplayClass4_0.<<PerformUpdateAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionImplAsync>d__6.MoveNext()
========== Finished ==========
Time Elapsed: 00:00:16.1334395

**Comment by karann-msft** [comment]
Use the appropirate repo for "product feedback"

![image](https://user-images.githubusercontent.com/16904420/55252026-19105a80-520f-11e9-9e70-c35540a4e5b5.png)
