### ISSUE TITLE
Timeout error while signing nuget packages

### ISSUE THREAD

**Issue by sameer-kumar** [NuGet/docs.microsoft.com-nuget#1655]
I'm following an article here https://docs.microsoft.com/en-us/nuget/create-packages/sign-a-package to sign my DotNet 48 nuget packages but couldn't. I get a timeout error:
`This operation returned because the timeout period expired`

I'm using code signing cert from GoDaddy.
This is my PowerShell task in TFS 2017.1 build pipeline:

```
Get-ChildItem $(PackageStagingDirectory)\nugetPackages -Filter "*.*nupkg" | ForEach-Object {
  $(Build.BinariesDirectory)\nuget.exe sign $_.FullName -Timestamper http://tsa.starfieldtech.com -CertificateFingerprint "$CertThumbprint" -OutputDirectory "$PkgOutputDir" -Overwrite -NonInteractive -Verbosity detailed
}
```

I don't see any option to bump up the timeout period.

Is this just me?

**Comment by sameer-kumar** [comment]
Problem was with GoDaddy TSA.

**Comment by sameer-kumar** [comment]
I'm experiencing this issue again hence re-opened. If I sign just one package, it works hower it times out with multiple package signing in a loop.

**Comment by sameer-kumar** [comment]
This is the error:

```
2019-09-04T16:13:30.6325997Z ##[error]This operation returned because the timeout period expired.

2019-09-04T16:13:30.6325997Z System.Security.Cryptography.CryptographicException: This operation returned because the timeout period expired.
2019-09-04T16:13:30.6325997Z 
2019-09-04T16:13:30.6325997Z    at NuGet.Packaging.Signing.Rfc3161TimestampRequest.SubmitRequest(Uri timestampUri, TimeSpan timeout)
2019-09-04T16:13:30.6325997Z    at NuGet.Packaging.Signing.Rfc3161TimestampProvider.GetTimestamp(TimestampRequest request, ILogger logger, CancellationToken token)
2019-09-04T16:13:30.6325997Z    at NuGet.Packaging.Signing.Rfc3161TimestampProvider.TimestampSignatureAsync(PrimarySignature primarySignature, TimestampRequest request, ILogger logger, CancellationToken token)
2019-09-04T16:13:30.6325997Z    at NuGet.Packaging.Signing.X509SignatureProvider.TimestampPrimarySignatureAsync(SignPackageRequest request, ILogger logger, PrimarySignature signature, CancellationToken token)
2019-09-04T16:13:30.6325997Z    at NuGet.Packaging.Signing.X509SignatureProvider.CreatePrimarySignatureAsync(SignPackageRequest request, SignatureContent signatureContent, ILogger logger, CancellationToken token)
2019-09-04T16:13:30.6325997Z    at NuGet.Packaging.Signing.SigningUtility.<SignAsync>d__4.MoveNext()
2019-09-04T16:13:30.6325997Z --- End of stack trace from previous location where exception was thrown ---
2019-09-04T16:13:30.6325997Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-09-04T16:13:30.6325997Z    at NuGet.Commands.SignCommandRunner.<ExecuteCommandAsync>d__1.MoveNext()
2019-09-04T16:13:31.1638153Z ##[error]Process completed with exit code 1 and had 1 error(s) written to the error stream.
```

**Comment by karann-msft** [comment]
@sameer-kumar - this is the docs repo and meant for issues on documentation. Use the Home repo to file product-related issues.
